name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  PORT: 8000
  DYNAMO_DB_Table: ${{ secrets.DYNAMO_DB_Table }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  REGION: ${{ secrets.REGION }}
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create env file
      run: |
        touch .env 
        echo PORT=${{ env.PORT }} >> .env 
        echo DYNAMO_DB_Table=${{ env.DYNAMO_DB_Table }} >> .env
        echo S3_BUCKET=${{ env.S3_BUCKET }} >> .env 
        echo USER_POOL_ID=${{ env.USER_POOL_ID }} >> .env 
        echo CLIENT_ID=${{ env.CLIENT_ID }} >> .env
        cat .env
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.ACCESS_KEY }}
        aws-secret-access-key: ${{ env.SECRET_KEY }}
        aws-region: ${{ env.REGION }}
    - name: list files
      run: ls -ltra
    - name: list files
      run: cat .env
    - name: Build the Docker image
      run: docker build -t krishiv-menon:latest .
    - name: Push to ECR
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ env.ACCESS_KEY }}
        secret-access-key: ${{ env.SECRET_KEY }}
        region: ${{ env.REGION }}
        local-image: krishiv-menon:latest
        image: krishiv-menon:latest
