name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  PORT: 8000
  DYNAMO_DB_Table: ${{ secrets.DYNAMO_DB_Table }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create env file
      run: |
        touch .env 
        PORT=${{ env.PORT }} >> .env 
        DYNAMO_DB_Table=${{ env.DYNAMO_DB_Table }} >> .env
        S3_BUCKET=${{ env.S3_BUCKET }} >> .env 
        USER_POOL_ID=${{ env.USER_POOL_ID }} >> .env 
        CLIENT_ID=${{ env.CLIENT_ID }} >> .env
    - name: Build the Docker image
      run: docker build -t krishiv-menon .
        - docker tag krishiv-menon:latest 484344126717.dkr.ecr.us-east-1.amazonaws.com/krishiv-menon:latest
        - docker push 484344126717.dkr.ecr.us-east-1.amazonaws.com/krishiv-menon:latest
